version: '3.8'

services:
  app:
    build:
      context:   # <-- This specifies the directory where the Dockerfile is located
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
